#ifndef eyeMode_glsl
#define eyeMode_glsl

#define RADIAL_FREQUENCY 0
#define RADIAL_WAVEFORM  1
#define RADIAL_FREQUENCY_HISTORY  2
#define ANGULAR_FREQUENCY 3
#define ANGULAR_WAVEFORM 4
#define ANGULAR_WAVEFORM_SYMMETRY 5
#define ANGULAR_WAVEFORM_RADIAL_FREQUENCY 6
#define SPIRAL_FREQUENCY 7
#define SPIRAL_FREQUENCY_HISTORY 8
#define ANGULAR_WAVEFORM_SPIRAL_FREQUENCY_HISTORY 9

#endif